# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude:
    - "G304: Potential file inclusion via variable"
    - "G107: Potential HTTP request made with variable url"
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goimports
    - gocritic
    - gofumpt
    - revive
linters-settings:
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - style
      - diagnostic
      - performance
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  revive:
    rules:
      - name: package-comments
        disabled: true
